### ISSUE TITLE
Multiple processes in background

### ISSUE THREAD

**Issue by D1N80** [S0nFra/StayAwakeApp#1]
Hi! Great project! 

I have seen there is the possibility of having multiple programs running in the background. 
![image](https://github.com/S0nFra/StayAwakeApp/assets/152190104/ed204362-d30d-4f9a-81a8-6337f4befa05)
Would it be better to make the application be run only once?
gg

**Comment by S0nFra** [comment]
Hi @D1N80! It is reasonable for only one instance of the application to be executed. With last commit (ebd53bf4408a4531710611348bda121ab7702872) I have solved this (tested on widows).

I'm closing this issue but fell free to reopen in case of problems.
